name: CI Pipeline

on:
push:
branches:
- main

jobs:
test:
runs-on: ubuntu-latest


steps:
  - name: Checkout code
    uses: actions/checkout@v3

  - name: Show files
    run: ls -R

  - name: Install backend dependencies
    run: |
      if [ -d "backend" ]; then
        cd backend
        npm install
      else
        echo "No backend folder found"
      fi

  - name: Done
    run: echo "Pipeline working ✅"

